# Generated by Django 4.2 on 2025-11-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('path', models.CharField(db_index=True, max_length=1000)),
                ('public_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('download_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('modified', models.CharField(blank=True, max_length=100)),
                ('media_type', models.CharField(default='file', max_length=100)),
                ('file_type', models.CharField(default='file', max_length=50)),
                ('search_vector', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'file_index',
            },
        ),
        migrations.AddIndex(
            model_name='fileindex',
            index=models.Index(fields=['name'], name='file_index_name_1d7945_idx'),
        ),
        migrations.AddIndex(
            model_name='fileindex',
            index=models.Index(fields=['path'], name='file_index_path_69f7db_idx'),
        ),
    ]
